markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: cui1994
author: "崔金涛"
email: 269584357@qq.com
name: "崔金涛个人博客"
url: http://cui1994.github.io
domain: cuijintao.github.io
all_categories: [ 
["work", "工作经验","/posts/work.html"],
["study", "学习笔记","/posts/study.html"], 
["other", "随笔","/posts/other.html"],
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
